name: caller

on:
  push:
    branches: [main]

jobs:
  caller-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call reusable workflow
        uses: ./.github/workflows/called.yml
        with:
          caller-path: "path/to/caller"
