name: caller

on:
  push:
    branches: [main]

jobs:
  caller-job:
    runs-on: ubuntu-latest
    outputs:
      called-output: ${{ steps.caller-workflow.outputs.called-output }}
    steps:
      - name: Trigger called workflow
        id: caller-workflow
        uses: ./.github/workflows/called.yml
        with:
          caller-path: "./caller"

      - name: Use called workflow output
        run: |
          echo "Output from called workflow: ${{ steps.caller-workflow.outputs.called-output }}"
