name: caller

on:
  push:
    branches: [main]

jobs:
  caller-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger called workflow
        uses: ./.github/workflows/called.yml
        with:
          caller-path: "./caller"
