name: Main
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  e2e-test:
    uses: hyung-rae/end-to-end/.github/workflows/e2e.yml@main

  build:
    needs: e2e-test
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [e2e-test, build]
    uses: ./.github/workflows/deploy.yml

  slack:
    needs: e2e-test
    if: always()
    uses: ./.github/workflows/slack.yml
    with:
      status: ${{ needs.e2e-test.test_result }}
    secrets:
      web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
